-- Course seed data for Cloud SQL import
-- Generated from assets/course-list.txt
-- Safe to run multiple times.

BEGIN;

WITH course_seed (course_code, course_name) AS (
  VALUES
    ('Philosophy', 'Philosophy')
    ,('History', 'History')
    ,('Literature', 'Literature')
    ,('Languages', 'Languages')
    ,('Linguistics', 'Linguistics')
    ,('Fine Arts', 'Fine Arts')
    ,('Music', 'Music')
    ,('Theater / Drama', 'Theater / Drama')
    ,('Film / Media Arts', 'Film / Media Arts')
    ,('Religious Studies', 'Religious Studies')
    ,('Sociology', 'Sociology')
    ,('Anthropology', 'Anthropology')
    ,('Psychology', 'Psychology')
    ,('Economics', 'Economics')
    ,('Political Science', 'Political Science')
    ,('International Relations', 'International Relations')
    ,('Geography', 'Geography')
    ,('Criminology', 'Criminology')
    ,('Social Work', 'Social Work')
    ,('Business Administration', 'Business Administration')
    ,('Management', 'Management')
    ,('Accounting', 'Accounting')
    ,('Finance', 'Finance')
    ,('Marketing', 'Marketing')
    ,('Entrepreneurship', 'Entrepreneurship')
    ,('Hospitality / Tourism Management', 'Hospitality / Tourism Management')
    ,('Law', 'Law')
    ,('Legal Studies', 'Legal Studies')
    ,('Public Administration', 'Public Administration')
    ,('Education', 'Education')
    ,('Elementary Education', 'Elementary Education')
    ,('Secondary Education', 'Secondary Education')
    ,('Special Education', 'Special Education')
    ,('Early Childhood Education', 'Early Childhood Education')
    ,('Mathematics', 'Mathematics')
    ,('Statistics', 'Statistics')
    ,('Physics', 'Physics')
    ,('Chemistry', 'Chemistry')
    ,('Biology', 'Biology')
    ,('Environmental Science', 'Environmental Science')
    ,('Earth Science', 'Earth Science')
    ,('Astronomy', 'Astronomy')
    ,('Mechanical Engineering', 'Mechanical Engineering')
    ,('Electrical Engineering', 'Electrical Engineering')
    ,('Electronics Engineering', 'Electronics Engineering')
    ,('Civil Engineering', 'Civil Engineering')
    ,('Chemical Engineering', 'Chemical Engineering')
    ,('Industrial Engineering', 'Industrial Engineering')
    ,('Computer Engineering', 'Computer Engineering')
    ,('Environmental Engineering', 'Environmental Engineering')
    ,('Computer Science', 'Computer Science')
    ,('Information Technology', 'Information Technology')
    ,('Information Systems', 'Information Systems')
    ,('Software Engineering', 'Software Engineering')
    ,('Data Science', 'Data Science')
    ,('Cybersecurity', 'Cybersecurity')
    ,('Medicine', 'Medicine')
    ,('Nursing', 'Nursing')
    ,('Pharmacy', 'Pharmacy')
    ,('Dentistry', 'Dentistry')
    ,('Public Health', 'Public Health')
    ,('Medical Technology / Laboratory Science', 'Medical Technology / Laboratory Science')
    ,('Nutrition & Dietetics', 'Nutrition & Dietetics')
    ,('Physical Therapy', 'Physical Therapy')
    ,('Agriculture', 'Agriculture')
    ,('Animal Science', 'Animal Science')
    ,('Forestry', 'Forestry')
    ,('Fisheries', 'Fisheries')
    ,('Food Science', 'Food Science')
    ,('Biotechnology', 'Biotechnology')
    ,('Architecture', 'Architecture')
    ,('Urban / Regional Planning', 'Urban / Regional Planning')
    ,('Interior Design', 'Interior Design')
    ,('Graphic Design', 'Graphic Design')
    ,('Industrial Design', 'Industrial Design')
    ,('Communication Studies', 'Communication Studies')
    ,('Journalism', 'Journalism')
    ,('Mass Communication', 'Mass Communication')
    ,('Public Relations', 'Public Relations')
    ,('Advertising', 'Advertising')
    ,('Liberal Arts', 'Liberal Arts')
    ,('General Studies', 'General Studies')
    ,('Interdisciplinary Studies', 'Interdisciplinary Studies')
)
INSERT INTO courses (
  course_code,
  course_name
)
SELECT
  course_code,
  course_name
FROM course_seed
ON CONFLICT (course_code)
DO UPDATE SET
  course_name = EXCLUDED.course_name;

COMMIT;
